#!/usr/bin/env python3
"""Generates the two documentation pages that must never disagree with the code.

    python scripts/build_docs.py            write them
    python scripts/build_docs.py --check    fail if they are stale (this is the CI gate)

Two pages, and both are generated for the same reason: a documentation page about a
tool, written by hand, is a snapshot of what the tool did on the day somebody wrote the
page. Every rule table in the world drifts, and the drift is invisible because both
halves look maintained.

    docs/quality-rules.md   every rule, rendered from `rules.py`
    examples/README.md      real skills, and the tool's REAL output over them

The examples are the golden corpus under `tests/fixtures/`, not a second set of demo
skills. A demo skill nobody runs rots the same way a hand-written table does; the corpus
is executed by `tests/run_tests.py` on every commit, so an example that stopped being
true fails the build before it reaches a reader.
"""
import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SQS = os.path.join(HERE, "sqs.py")
FIXTURES = os.path.join(REPO, "tests", "fixtures")
sys.path.insert(0, HERE)

from rules import MODULES, RULES, module_of          # noqa: E402

GENERATED = "<!-- generated by scripts/build_docs.py - edit that, not this -->"

MODULE_BLURB = {
    "spec": ("Agent Skills specification conformance. Everything here is something a "
             "skill survives locally and fails on publication, which is why it is a "
             "separate pass: the author never sees it until it is too late."),
    "structure": ("Links, orphans, budgets, section pointers, outbound paths. This is the "
                  "class of defect that breaks **today, in silence**: a broken pointer "
                  "into `references/` crashes nothing, the agent just skips the step."),
    "quality": ("Whether the instructions read like instructions. The module with the "
                "most room to lie, so every rule here names a file and a line."),
    "compat": ("Whether the skill will work on somebody else's harness. `UNKNOWN` is "
               "never `NOT_SUPPORTED`: where a project's documentation is silent, the "
               "answer is unknown rather than an invented incompatibility."),
    "security": ("What an installed skill can do to the machine that loads it. A skill is "
                 "executable text, and an installed skill is a supply chain."),
    "publish": ("What has to be true before the skill leaves the machine it was written "
                "on. Half of these are correct-and-intended for a skill that stays home."),
    "evals": ("Whether anything would notice the skill breaking: the eval files, the "
              "routing invariants, and the agent runs behind `sqs.py eval`."),
}


RULES_FRONTMATTER = [
    "---",
    'title: "Quality rules - every check an Agent Skill validator runs"',
    "description: >-",
    "  The full rule list of skill-quality-suite: specification conformance, structure,",
    "  instruction quality, cross-harness compatibility, security, publishing and evals,",
    "  each with its reasoning, its fix, its detection confidence and its false-positive",
    "  risk.",
    "---",
    "",
]


def render_rules():
    out = RULES_FRONTMATTER + [GENERATED, "", "# Quality rules",
           "",
           f"Every finding the suite can emit, all {len(RULES)} of them, rendered from "
           f"`scripts/rules.py`.",
           "",
           "`sqs.py explain <CODE>` prints the same reasoning at the terminal, and "
           "`sqs.py rules --module security` lists one module.",
           "",
           "Each rule carries two gradings that are about **the check**, not about the "
           "skill:",
           "",
           "- **confidence** - how reliably the check finds the thing it names. A "
           "filesystem fact or a parse is `high`; a regex over prose is `medium`; a "
           "similarity heuristic is `low`.",
           "- **false positives** - when the thing *is* there, how often it is "
           "nonetheless intended. `README.md` inside a skill folder is a finding and also "
           "exactly what a repository-shaped skill does.",
           "",
           "`--min-confidence high` keeps the facts and drops the heuristics, which is "
           "the gate you can leave switched on in CI.",
           ""]
    for prefix, module in sorted(MODULES.items(), key=lambda kv: kv[1]):
        codes = sorted(c for c in RULES if module_of(c) == module)
        if not codes:
            continue
        out += [f"## {module} ({prefix}xxx)", "", MODULE_BLURB.get(module, ""), "",
                "| Code | Severity | Confidence | False positives | Autofix | What it is |",
                "|---|---|---|---|---|---|"]
        for code in codes:
            r = RULES[code]
            out.append(f"| `{code}` | {r.severity} | {r.confidence} | "
                       f"{r.false_positive_risk} | {'yes' if r.fixable else 'no'} | "
                       f"{r.title} |")
        out.append("")
        for code in codes:
            r = RULES[code]
            out += [f"### {code} - {r.title}", "", f"**Why it matters.** {r.why}", "",
                    f"**Fix.** {r.how}", ""]
    return "\n".join(out).rstrip() + "\n"


def run(args, cwd=None, env=None):
    r = subprocess.run([sys.executable, SQS] + args, capture_output=True, text=True,
                       encoding="utf-8", errors="replace", cwd=cwd or REPO,
                       env=dict(os.environ, PYTHONIOENCODING="utf-8", **(env or {})))
    return (r.stdout + r.stderr).strip()


def case_output(case, *extra):
    """The suite's real output over one fixture case."""
    path = os.path.join(FIXTURES, case)
    return run(["check", "--skills-dir", path] + list(extra),
               env={"CLAUDE_SKILLS_DIR": path})


def read(*parts):
    with open(os.path.join(FIXTURES, *parts), encoding="utf-8") as f:
        return f.read().rstrip()


def fix_before_after(case, skill, filename="SKILL.md"):
    """(before, after, what the fixer said) for a case `sqs.py fix` can repair."""
    src = os.path.join(FIXTURES, case)
    with tempfile.TemporaryDirectory() as tmp:
        work = os.path.join(tmp, "tree")
        shutil.copytree(src, work)
        before = open(os.path.join(work, skill, filename), encoding="utf-8").read()
        said = run(["fix", "--skills-dir", work, "--apply"], env={"CLAUDE_SKILLS_DIR": work})
        after = open(os.path.join(work, skill, filename), encoding="utf-8").read()
    return before, after, said


def scan_materialised(case, command="check", *extra):
    """Run a module over a fixture with its generated payloads applied.

    The materialising is imported from `tests/run_tests.py` rather than reimplemented:
    two copies of the payload assembly would drift, and the drift would show up as a
    documentation page quietly disagreeing with the tests.
    """
    sys.path.insert(0, os.path.join(REPO, "tests"))
    import run_tests                                            # noqa: PLC0415
    with open(os.path.join(FIXTURES, case, "expect.json"), encoding="utf-8") as f:
        spec_ = json.load(f)
    with tempfile.TemporaryDirectory() as work:
        root = run_tests.materialise(os.path.join(FIXTURES, case), spec_, work)
        return run([command, "--skills-dir", root] + list(extra),
                   env={"CLAUDE_SKILLS_DIR": root}).replace(root, f"tests/fixtures/{case}")


def fence(text, lang=""):
    return f"```{lang}\n{text}\n```"


def render_examples():
    clean = read("clean", "tidy-notes", "SKILL.md")
    broken = read("quality-prose", "vague-steps", "SKILL.md")
    before, after, said = fix_before_after("spec-frontmatter", "renamed-folder")
    diff = "\n".join(difflib.unified_diff(
        before.split("\n"), after.split("\n"),
        fromfile="renamed-folder/SKILL.md (before)",
        tofile="renamed-folder/SKILL.md (after)", lineterm="", n=2))
    # The insecure fixture is inert in git - its dangerous lines are assembled at run
    # time, because this repository is itself a skill and ships into everyone's skills
    # directory. So the page has to materialise it exactly as the corpus runner does,
    # through the same function: scanning the checked-in file would print a clean report
    # under a paragraph promising six findings, which is the one output this project
    # exists to prevent.
    malicious = scan_materialised("malicious", "security")

    return "\n".join([
        GENERATED, "",
        "# Examples", "",
        "Real skills, and the tool's real output over them. Everything on this page is "
        "generated by `scripts/build_docs.py` from the test corpus under "
        "[`tests/fixtures/`](../tests/fixtures), which "
        "[`tests/run_tests.py`](../tests/run_tests.py) executes on every commit. An "
        "example that stopped being true fails the build before it reaches you.", "",
        "```bash",
        "python scripts/sqs.py check ./my-skill        # the everyday five",
        "python scripts/sqs.py security ./my-skill     # before you run a stranger's skill",
        "python scripts/sqs.py fix ./my-skill --apply  # the repairs with one right answer",
        "```", "",
        "## A skill with nothing wrong with it", "",
        f"The negative case for all {len(RULES)} rules at once. Any finding here would be a false "
        "positive, which is why the corpus asserts this one reports **nothing at all**.",
        "", fence(clean, "markdown"), "",
        "```", "$ sqs.py check tests/fixtures/clean", case_output("clean") or "(no output)",
        "```", "",
        "## A skill that loads and underperforms", "",
        "Nothing here crashes. The skill activates, and the work comes out thinner than "
        "it should have - which is the failure mode this whole suite exists to make "
        "loud.", "", fence(broken, "markdown"), "",
        "```", "$ sqs.py check tests/fixtures/quality-prose",
        case_output("quality-prose"), "```", "",
        "Each code carries its reasoning:", "",
        "```", "$ sqs.py explain QL002", run(["explain", "QL002"]), "```", "",
        "## Before and after `sqs.py fix --apply`", "",
        "The fixer only repairs what the broken state forces - the name the folder "
        "already dictates, characters that should never have been in the file. It "
        "deliberately will not shorten an over-long description: there is no single "
        "right shortening, and picking one for you deletes a trigger you needed.", "",
        "```", "$ sqs.py fix tests/fixtures/spec-frontmatter --apply", said, "```", "",
        fence(diff, "diff"), "",
        "## A skill you should not run yet", "",
        "This is what `sqs.py security` is for: a skill somebody else wrote, read "
        "**before** the agent reads it for work. The fixture reads as helpful and does "
        "six things at once - a download piped into a shell, a recursive delete, a "
        "credential file posted to an endpoint, a token committed in the text, an "
        "instruction addressed at the agent rather than at the task, and a line of "
        "invisible control characters that make the rendered file differ from the file "
        "the model reads.", "",
        "```", "$ sqs.py security tests/fixtures/malicious", malicious, "```", "",
        "The file itself is [`tests/fixtures/malicious/`]"
        "(../tests/fixtures/malicious). It is not reproduced here: it carries a "
        "token-shaped string on purpose, and pasting that into a README is how a "
        "repository gets its next push blocked by somebody else's secret scanner.", "",
        "## The board, for deciding rather than fixing", "",
        "```", "$ sqs.py check tests/fixtures/quality-prose --format board",
        case_output("quality-prose", "--format", "board"), "```", "",
        "`NOT RUN` is the point of that view. A layer that was skipped and a layer that "
        "passed look identical in a findings list, and that is how a report comes to say "
        "\"clean\" about a question nobody asked.", "",
    ]).rstrip() + "\n"


TARGETS = [("docs/quality-rules.md", render_rules), ("examples/README.md", render_examples)]


def main(argv=None):
    ap = argparse.ArgumentParser(description="generate the pages that must not drift")
    ap.add_argument("--check", action="store_true", help="fail when a page is stale")
    a = ap.parse_args(argv)
    stale = []
    for rel, render in TARGETS:
        path = os.path.join(REPO, rel)
        want = render()
        have = None
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                have = f.read()
        if a.check:
            if have != want:
                stale.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(want)
        print(f"wrote {rel} ({len(want)} bytes)")
    if a.check:
        for rel in stale:
            print(f"{rel} is stale - run `python scripts/build_docs.py`", file=sys.stderr)
        if not stale:
            print("generated pages are current")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
